package filius.gui.anwendungssicht;

import filius.software.wannacry.WannaCry;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Observable;

public class GUIApplicationWannaCry extends GUIApplicationWindow{

    private static final long serialVersionUID = 1L;
    private JPanel backpanel;

    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JScrollPane descriptionPane;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;

    public GUIApplicationWannaCry(GUIDesktopPanel desktop, String appKlasse) {
        super(desktop, appKlasse);
        initComponents();
        this.getContentPane().add(backpanel);
        pack();
    }

    // Generated by Netbeans
    private void initComponents() {

        backpanel = new JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        descriptionPane = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        startButton = new javax.swing.JButton();

        backpanel.setBackground(new java.awt.Color(204, 0, 51));

        titlePanel.setBackground(new java.awt.Color(204, 0, 51));
        titlePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("WannaCry Starter");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
                titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(titlePanelLayout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(titleLabel)
                                .addContainerGap(301, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
                titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(titlePanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(titleLabel)
                                .addContainerGap(46, Short.MAX_VALUE))
        );

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        descriptionArea.setText("Welcome to the WannaCry Demonstration.\nIf you click the start-button the following processes starts in the background\n1. The Dropper starts to infect this system\n2. The Ransomware will encrypt the files on this systems\n3. The Dropper starts to guess other available Systems in the network and use Eternalblue to infect them");
        descriptionPane.setViewportView(descriptionArea);
        descriptionArea.setEditable(false);

        startButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        startButton.setText("Start");
        startButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                ((WannaCry) holeAnwendung()).startWannaCryAttack();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(backpanel);
        backpanel.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(descriptionPane)
                                        .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(descriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE))
        );
    }

    @Override
    public void update(Observable o, Object arg) {

    }
}
